### PR TITLE
Add initial build run

### PR DESCRIPTION
**Pull request by slide**
Add an initial build for the new job to make sure everything is setup correctly.

### CODE REVIEW

**Comment by aheritier** [comment]
@slide it was a good idea this improvement
I don't know why it wasn't merged
I discovered yesterday that it wasn't the case and I had to trigger a build for all new jobs "manually"

**Comment by slide** [comment]
I can rebase and resubmit.

**Comment by aheritier** [comment]
+1

**Comment by slide** [comment]
Superseded by #3

**Pull request closed without merging**
